# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

---
- name: Start of CI/CD pipeline
  hosts: Dev
  gather_facts: false

    
  roles:
    - presentation


- name: Aggregate test results
  hosts: localhost
  tasks:
    - name: Check if tests are done
      find:
        path: roles/presentation/files/reports
        pattern: "*.xml"
      register: presentation_test_result

    - debug: 
        msg: "No reports found"
      when: presentation_test_result.matched == 0

    - name: "Publishing reports" 
      local_action: shell rebot --output presentation_unittest.xml --log presentation_unittest_log.html --report presentation_unittest_report.html --outputdir ../ *.xml 
      args:
        chdir: roles/presentation/files/reports
      when: presentation_test_result.matched != 0 
...
