output "id" {
    description = "Value generated by the back-end to uniquely identify a compartment"
    value = data.azurerm_subnet.subnet.id
}

output "subnet" {
    description = "Value generated by the back-end providing the subnet of the compartment"
    value = azure_compartments.compartment.subnet
}

output "subnetmask" {
    description = "Value generated by the back-end providing the subnetmask for the compartment"
    value = azure_compartments.compartment.subnetmask
}
